PPWProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

#from story6App.views import index as indexx
from story6App.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story6App/', include('story6App.urls', namespace='story6App')),#, namespace='story6App'))
    path('', include('story6App.urls', namespace='index')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

story6App/urls.py
from django.conf.urls import url
from django.urls import path

from .views import index, forms_post, myProfile, myLibrary, jsonLibrary, registrasi, registrationRender, validate_email, registrationData, unSubscribe, logOutViews

app_name = 'story6App'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^forms_post', forms_post, name='forms_post'),
    url(r'^my-profile', myProfile, name='challenge6'),
    url(r'^my-library', myLibrary, name='myLibrary'),
    # url(r'^json-library', jsonLibrary, name='jsonLibrary'),
    path('json-library/<kategori>', jsonLibrary, name='jsonLibrary'),
    url(r'^registrasi_post', registrasi, name='registrasi_post'),
    url(r'^registrasi', registrationRender, name='registrasi'),
    url(r'validate_email', validate_email, name='validate_email'),
    url(r'^registration-data', registrationData, name='registration-data'),
    url(r'^unsubscribe', unSubscribe, name='unSubscribe'),
    url(r'^log-out', logOutViews, name='logout')
]

story6App/models.py
from django.db import models

# Create your models here.
class formModels(models.Model):
    status = models.CharField(max_length=300)

class formRegistrasiModels(models.Model):
    nama = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=30)

story6App/forms.py
from django import forms

class formStatus(forms.Form):
    attrs = {'class': 'form-control'}
    status = forms.CharField(label='Status', required=True, max_length=300, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))

class formRegistrasi(forms.Form):
    nama = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs={'class' : 'form-control',
                                                                                                     'placeholder' : 'Nama'}))
    email = forms.EmailField(label='', required=True, max_length=30, widget=forms.TextInput(attrs={'class' : 'form-control',
                                                                                                       'type' : 'email',
                                                                                                       'placeholder' : 'Alamat Email'}))
    password = forms.CharField(label='', required=True, max_length=30,  widget=forms.TextInput(attrs={'class' : 'form-control',
                                                                                                              'type' : 'password',
                                                                                                              'placeholder' : 'Password'}))

story6App/views.py
from django.contrib.auth import logout
from django.shortcuts import render
from django.http import HttpResponseRedirect, response, JsonResponse, HttpResponse
from django.urls import reverse
import json

from .forms import formStatus, formRegistrasi
from .models import formModels, formRegistrasiModels
import requests
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
#diary_dict = {}
def index(request):
    isiForms = formModels.objects.all()
    response = {'forms' : formStatus, 'result': isiForms}
    return render(request, "lab6.html", response)

def forms_post(request):
    response = {}
    if(request.method == "POST" or None):
        response['status'] = request.POST['status']
        forms = formModels(status=response['status'])
        forms.save()
        return HttpResponseRedirect(reverse('index:index'))
    else:
        return HttpResponseRedirect('/')
        
def myProfile(request):
    return render(request, 'myProfile.html')

def myLibrary(request):
    return render(request, 'myLibrary.html')

def jsonLibrary(request, kategori=None):
    url = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + str(kategori))
    urlJson = url.json()
    return JsonResponse(urlJson)

def registrasi(request):
    response = {}
    if(request.method == "POST" or None):
        response['nama'] = request.POST['nama']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        forms = formRegistrasiModels(nama=response['nama'], email=response['email'], password=response['password'])
        forms.save()
    return JsonResponse({})

def registrationRender(request):
    isiForms = formRegistrasiModels.objects.all()
    response = {'forms' : formRegistrasi, 'result_registrasi': isiForms}
    return render(request, "registrasi.html", response)

def validate_email(request):
    email = request.POST.get('email', None)
    data = {
        'is_taken': formRegistrasiModels.objects.filter(email=email).exists()
    }
    return JsonResponse(data)

def registrationData(request):
    isiForms = formRegistrasiModels.objects.all()
    sub_list = [{'nama' : e.nama, 'email' : e.email} for e in isiForms]
    return HttpResponse(json.dumps({'data': sub_list}))

def unSubscribe(request):
    email = request.POST.get('email')
    formRegistrasiModels.objects.filter(email=email).delete()
    return HttpResponse("x")

def logOutViews(request):
    logout(request)
    return HttpResponseRedirect("/my-library")






# My Library Ga jadi :) #
# def myLibrary(request):
#     titles = list()
#     url = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
#     urlJson = url.json()
#     response['buku'] = urlJson
#     for i in range (urlJson):
#         titles.append(urlJson['items'][i]['volumeInfo']['title'])
#     return render(request, 'myLibrary.html', response)

story6App/templates/lab6.html
<!DOCTYPE html>
<html>
    <head>
        <title>Status</title>
        {% include "partials/header.html" %}
    </head>
    <body>
        <div class="container" align="center">
            <h1>Hello Apa kabar?</h1>
            <div>
                <form action={% url 'story6App:forms_post' %} method="POST">
                    {% csrf_token %}
                    {{ forms.as_p }}
                    <input type="submit" value="Submit">
                </form>
            </div>
            <div>
                <thead>
                    <th>Status : </th>
                </thead>
                <tbody>
                    {% for i in result %}
                        <td> {{i.status}}; </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </div>

            <!--<p>*halaman profil = ppw-f-haq.herokuapp.com/my-profile</p>-->
        </div>
    </body>
</html>

story6App/templates/myLibrary.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library</title>
    {% include "partials/header.html" %}
</head>
<body>
    <div class="container" align="right" style="padding-top: 10px">
        {% block content %}
        {% if user.is_authenticated %}
                 <p class="display-4" style="font-family: Georgia">Halo, {{ user.username }} !</p>
                <a type="button" class="btn btn-danger" href="{% url 'index:logout' %}">Logout</a>
        {% else %}
                 <a type="button" class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Log in with Google</a>
        {% endif %}
    </div>
{% endblock content %}

    <div class="container container-judul">
        <h1>LIBRARY</h1>
    </div>
    <div class="container container-change">
       <button type="button" class="btn btn-info" onclick="changeCategory('quilting')">Quilting</button>
        <button type="button" class="btn btn-info" onclick="changeCategory('comic')">Comic</button>
        <button type="button" class="btn btn-info" onclick="changeCategory('architecture')">Architecture</button>
    </div>

    <div class="container container-counter">
        <h5 id="jumlah-favorit">Jumlah buku favorit : 0</h5>
    </div>
    <div class="container container-library">
        <table id="list-buku">
            <tr id="table-header">
                <th>Sampul</th>
                <th>Judul</th>
                <th>Penulis</th>
                <th>Deskripsi</th>
                <th>Favorit</th>
            </tr>
        </table>
    </div>
</body>
</html>

story6App/templates/myProfile.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>My Profile</title>
        {% include "partials/header.html" %}
    </head>
    <body onload="showpage()">
        <div id="preload" align="center">
            <img id="loading-image" src="http://themenectar.com/docs/salient/wp-content/uploads/2016/10/basicloader.gif">
        </div>
        <div id="content" style="display: none">
            <div class="container profile-info" align="center">
                <div class="profile-img">
                    <img src="https://pbs.twimg.com/profile_images/1042423648437469185/N0XYJ4W2_400x400.jpg" class="gambar rounded-circle img-fluid">
                </div>
                <div class="profile-text">
                    <h5>Nama : Muhammad Dhiyaulhaq Nugraha</h5>
                    <h5>Tanggal Lahir : 4 November 1999</h5>
                    <h5>Hobi : Badminton</h5>
                </div>
            </div>
            <div class="container container-accordion" align="center">
                <div id="accordion">
                    <h3>Aktivitas</h3>
                    <div>
                        <p>Kuliah</p>
                        <p>Tidur</p>
                        <p>Makan</p>
                        <p>Ibadah</p>
                    </div>
                    <h3>Pengalaman</h3>
                    <div>
                        <p>SBF PSDM</p>
                        <p>Mentor OKK UI 2018</p>
                        <p>Staff Seminar COMPFEST X</p>
                        <p>VPJ Penunjang SIWAK NG 2018</p>
                    </div>
                    <h3>Prestasi</h3>
                    <div>
                        Ga ada kayaknya deh hehe
                    </div>
                </div>
            </div>

            <div class="container" align="center">
                <div class="tombol" style="padding-top: 20px">
                    <button id="tombol" type="button" class="btn btn-primary">Ubah Tema</button>
                </div>
            </div>
        </div>
    </body>
</html>

story6App/templates/partials/header.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script type="text/javascript" src="{% static 'js/myJS.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/myCSS.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
    <meta name="google-signin-client_id" content="1057832288973-h80jdnlepk4qj4rg9ca20hcjb9vu83ad.apps.googleusercontent.com">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story6App:forms_post' %}">Status<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story6App:challenge6' %}">Profil<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story6App:myLibrary' %}">Library<span class="sr-only">(current)</span></a>
                </li>
                 <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story6App:registrasi' %}">Registrasi<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
</body>
</html>

story6App/templates/registrasi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrasi</title>
    {% include "partials/header.html" %}
</head>
<body>
    <div class="container" align="center" style="padding-top: 20px">
        <h1>REGISTRASI</h1>
    </div>
    <div class="container container-registrasi" style="padding-top : 20px; width: 50%" align="center">
        <div>
            <form action={% url 'story6App:registrasi' %} method="POST">
            {% csrf_token %}
            {{ forms.as_p }}
            </form>
            <input id="btn_submit" class="btn btn-primary" name="id_submit" type="submit" value="Submit" onclick="submit_post()" data-toggle="modal" data-target="#myModal" disabled>
        </div>
    </div>

    <div class="container container-library" style="padding-top : 30px;" align="center">
        <div>
            <h5>LIST SUBSCRIBER</h5>
        </div>
        <table id="list-subscriber">
            <tr id="table-header">
                <th>Nama</th>
                <th>Email</th>
                <th>Unsubscribe</th>
            </tr>
        </table>
    </div>

    <div class="container">
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">SUKSES !</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        Data anda berhasil tersimpan ...
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>

    </div>
</body>
</html>